Repository kalviumcommunity/S74_Yogesh_Capstone_Guessync, pull requests merged in 2025-06, with the labels that each got.

#5 Frontend Initialized
  client/.gitignore
  client/README.md
  client/eslint.config.js
  client/index.html
  client/package-lock.json
  client/package.json
  client/public/vite.svg
  client/src/App.css
  client/src/App.jsx
  client/src/assets/react.svg
  client/src/index.css
  client/src/main.jsx
  client/vite.config.js
Labels: Review effort 2/5

#16 Implement GET /me and GET /by-index API endpoints
  server/config/db.js
  server/routes/authRoutes.js
  server/routes/songRoutes.js
  server/server.js
Labels: Review effort 2/5

#18 Added Mongoose schemas for Room, Song, and User models
  server/models/Room.js
  server/models/Song.js
  server/models/User.js
Labels: Review effort 2/5

#20 Re-add roomController.js with full DB read/write logic
  server/controllers/roomController.js
Labels: Review effort 3/5, Possible security concern

#26 Using Firebase JWT tokens in application
  client/src/config/firebase.js
  client/src/context/AuthContext.jsx
  client/src/pages/Login.jsx
  server/config/firebase.js
  server/routes/roomRoutes.js
Labels: Possible security concern, Review effort 4/5

#27 Added 6 unit tests using Vitest & Testing Library
  client/src/tests/JoinRoom.test.jsx
Labels: Review effort 2/5

#28 Added Dockerfile to containerize app
  server/Dockerfile
Labels: Review effort 2/5, Possible security concern

#35 added typing effect to about dev title (#3)
  client/src/pages/AboutDev.jsx
Labels: Review effort 2/5

#36 added remaining frontend pages (GameRoom, LandingPage, JoinRoom, etc.)
  client/src/App.jsx
  client/src/data/avatarList.js
  client/src/pages/GameRoom.jsx
  client/src/pages/HomePage.jsx
  client/src/pages/JoinRoom.jsx
  client/src/pages/LandingPage.jsx
  client/src/pages/WaitingRoom.jsx
Labels: Possible security concern, Review effort 4/5

#42 Set up Firebase Admin SDK using .env
  server/config/firebase-adminsdk.js
  server/config/firebase.js
Labels: Review effort 3/5, Possible security concern
